### ISSUE TITLE
App flashes when authorized to read contacts ？

### ISSUE THREAD

**Issue by ChenJiaXu** [apache/cordova-plugin-contacts#176]
```
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{1daa3c0 5625:{packname}/u0a508} (pid=5625, uid=10508) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4287)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5672)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2278)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1533)
	at android.content.ContentResolver.query(ContentResolver.java:518)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at org.apache.cordova.contacts.ContactAccessorSdk5.search(ContactAccessorSdk5.java:196)
	at org.apache.cordova.contacts.ContactManager$3.run(ContactManager.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
```

Some people say that it is a sdk problem, there are corresponding programs, but I will not develop Android, so I can't understand how to modify it.

This problem occurs in the miui system, which is the Chinese Android custom system for Xiaomi.

The following is the corresponding solution I found, but after the tutorial is modified, the compiler package will report an error, I think there is a problem with the method or what jar package is missing.
https://blog.csdn.net/OREO_GO/article/details/52295099
https://blog.csdn.net/waww116529/article/details/77719531

**Comment by ChenJiaXu** [comment]
> Your error indicates: requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
> 
> Did you request permission to the user to even access their contacts? You cannot just access a user his contacts without permission (privacy!). You can use the diagnostic plugin to check if user provided permission or ask permission: https://github.com/dpa99c/cordova-diagnostic-plugin#iscontactsauthorized

I have used the cordova request permission plugin in the code to get the judgment. When I open the app for the first time and pop up the authorization interface, a flashback event will cause the app to be reopened to be used normally. You can look at the error message I provided. Someone in China encountered the same error. The specific reason seems to be sdk22 or above. I also provided two link addresses, which provide solutions, but I will modify it after reference. I can't solve my problem, so I hope I can get help from you.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
